services:
  # BD
  banco:
    image: mariadb:10.11
    container_name: container_banco
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senhadoroot
      MYSQL_DATABASE: projeto_web
      MYSQL_USER: usuario_projeto
      MYSQL_PASSWORD: senhadousuario
    volumes:
      - dados-db:/var/lib/mysql
      - ./banco/projeto_web.sql:/docker-entrypoint-initdb.d/projeto_web.sql
    networks:
      - infra-network

  # INSTÂNCIA 1 (APP1)
  app1:
    build: ./backend
    container_name: app_instancia_1
    restart: always
    environment:
      - DB_HOST=banco
      - DB_USER=root
      - DB_PASSWORD=senhadoroot
      - DB_NAME=projeto_web
      - DB_PORT=3306
    depends_on:
      - banco
    networks:
      - infra-network
    # removida a propriedade "ports". O app1 ta isolado na rede interna

  # INSTÂNCIA 2 (APP2)
  app2:
    build: ./backend
    container_name: app_instancia_2
    restart: always
    environment:
      - DB_HOST=banco
      - DB_USER=root
      - DB_PASSWORD=senhadoroot
      - DB_NAME=projeto_web
      - DB_PORT=3306
    depends_on:
      - banco
    networks:
      - infra-network
    # o app2 usa o mesmo código, mas roda como conteiner separado

  # BALANCEADOR DE CARGA (NGINX)
  nginx:
    image: nginx:latest
    container_name: container_nginx
    restart: always
    ports:
      - "80:80" # ÚNICO serviço exposto para o pc (localhost)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - infra-network

networks:
  infra-network:
    driver: bridge

volumes:
  dados-db: